// <auto-generated />
namespace ExerciseEf6.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InsertedUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InsertedUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "201610311239467_Inserted Users"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
