// <auto-generated />
namespace Time4Time3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IsActive_Service : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsActive_Service));
        
        string IMigrationMetadata.Id
        {
            get { return "201611161741405_IsActive_Service"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
